spring:
  application:
    name: companies-crud
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    default: default

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  servlet:
    context-path: /companies-crud
  port: 0

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE